runmode: debug                 # 开发模式, debug, release, test
port: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password:
docker_db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password:
gormlog: true
tls:
  port: :8081
  cert: conf/server.crt
  key: conf/server.key
